plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.andrearanttes99.treino'
    compileSdk 34

    defaultConfig {
        applicationId 'io.github.andrearanttes99.treino'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
